version: "3.8"
services:
  action:
    build:
      context: ./Action
      dockerfile: Dockerfile
    ports:
      - "4049:4049"
    volumes:
      - ./Action/workspaces:/action_workspace
    working_dir: /action_workspace
    command: sleep infinity

    environment:
      CHOKIDAR_USEPOLLING: 1

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/devices
