version: "3.8"
services:
  action:
    build:
      context: ./Action
      dockerfile: Dockerfile
    ports:
      - "4049:4049"
    volumes:
      - ./Action/workspace:/action_workspace:cached
    env_file:
      - ./Action/.env.docker

  svelte-flow:
    build:
      context: ./SvelteFlow
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./SvelteFlow/workspace:/svelte_flow_workspace

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/devices
