version: "3.8"
services:
  routine:
    build:
      context: ./Routine
      dockerfile: Dockerfile
    ports:
      - "4049:4049"
      - "8080:8080"
    volumes:
      - ./Routine/workspace:/routine_workspace
    stdin_open: true
    tty: true

  svelte-flow:
    build:
      context: ./SvelteFlow
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./SvelteFlow/workspace:/svelte_flow_workspace
      - /svelte_flow_workspace/node_modules
    stdin_open: true
    tty: true

  llm-app-server:
    image: python:alpine
    container_name: llm-app-server
    ports:
      - "8800:8800"
    volumes:
      - ./app:/app # 必要に応じてアプリケーションコードをマウントする
      - ./llm-app/config:/app/config # 構成ファイルのマウント (必要に応じて)

  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/devices
